#!/usr/bin/env npx tsx
/**
 * Bulk import CAS numbers for ingredients that have PubChem hits.
 *
 * Uses CAS Common Chemistry API to resolve ingredient names → CAS Registry Numbers.
 * Only processes names that already exist in the reference DB (have PubChem data).
 *
 * Usage:
 *   npx tsx scripts/import-cas.ts
 *
 * Input:  Queries D1 for names with PubChem data (falls back to seed list)
 * Output: scripts/d1-ingredients-ref-cas.sql
 *
 * Then import:
 *   npx wrangler d1 execute consumer-truth-ingredients-ref --remote --file=scripts/d1-ingredients-ref-cas.sql
 */

import { readFileSync, createWriteStream } from 'fs'
import { execSync } from 'child_process'
import path from 'path'

const INPUT_FILE = path.join(process.cwd(), 'scripts', 'ingredient-seed-list.json')
const OUTPUT_FILE = path.join(process.cwd(), 'scripts', 'd1-ingredients-ref-cas.sql')
const DB_NAME = 'consumer-truth-ingredients-ref'

const CONCURRENCY = 2 // CAS allows ~2 req/sec
const BATCH_DELAY_MS = 1100 // delay between concurrent batches
const FETCH_TIMEOUT = 10000

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''")
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function fetchCAS(name: string): Promise<string | null> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT)

  try {
    const url = `https://commonchemistry.cas.org/api/search?q=${encodeURIComponent(name)}`
    const res = await fetch(url, {
      headers: {
        'User-Agent': 'ConsumerTruth-Import/1.0',
        'Accept': 'application/json',
      },
      signal: controller.signal,
    })

    clearTimeout(timeout)

    if (!res.ok) return null

    const data = await res.json()
    if (data.count > 0 && data.results?.[0]?.rn) {
      return data.results[0].rn
    }
    return null
  } catch {
    clearTimeout(timeout)
    return null
  }
}

async function getNamesWithPubChem(): Promise<string[]> {
  try {
    const result = execSync(
      `npx wrangler d1 execute ${DB_NAME} --remote --command "SELECT name FROM ingredient_reference WHERE pubchem_cid IS NOT NULL" --json`,
      { encoding: 'utf-8', maxBuffer: 100 * 1024 * 1024 }
    )
    const parsed = JSON.parse(result)
    const rows = parsed?.[0]?.results || []
    return rows.map((r: any) => r.name)
  } catch (e) {
    console.log('Could not query D1 for PubChem names, falling back to full seed list')
    return JSON.parse(readFileSync(INPUT_FILE, 'utf-8'))
  }
}

async function main() {
  console.log('Getting ingredient names with PubChem data...')
  const names = await getNamesWithPubChem()
  console.log(`Processing ${names.length} ingredients`)
  console.log(`Estimated time: ${((names.length / CONCURRENCY * BATCH_DELAY_MS) / 1000 / 60).toFixed(0)} minutes`)

  const out = createWriteStream(OUTPUT_FILE)
  out.write('-- CAS number import for ingredients reference\n')
  out.write('-- Auto-generated by import-cas.ts\n\n')

  let hits = 0
  let misses = 0
  const startTime = Date.now()

  for (let i = 0; i < names.length; i += CONCURRENCY) {
    const batch = names.slice(i, i + CONCURRENCY)

    const results = await Promise.all(
      batch.map(async (name) => {
        try {
          const cas = await fetchCAS(name)
          return { name, cas }
        } catch {
          return { name, cas: null }
        }
      })
    )

    for (const { name, cas } of results) {
      if (cas) {
        hits++
        out.write(
          `UPDATE ingredient_reference SET cas_number = '${escapeSQL(cas)}', updated_at = datetime('now') WHERE name = '${escapeSQL(name.toLowerCase())}';\n`
        )
      } else {
        misses++
      }
    }

    const processed = Math.min(i + CONCURRENCY, names.length)
    if (processed % 200 < CONCURRENCY || processed === names.length) {
      const elapsed = (Date.now() - startTime) / 1000
      const rate = processed / elapsed
      const remaining = (names.length - processed) / rate
      console.log(
        `Progress: ${processed}/${names.length} (${hits} hits, ${misses} misses) ` +
        `[${rate.toFixed(1)} names/sec, ~${(remaining / 60).toFixed(0)} min remaining]`
      )
    }

    await sleep(BATCH_DELAY_MS)
  }

  out.end()

  const totalTime = ((Date.now() - startTime) / 1000 / 60).toFixed(1)
  console.log(`\nDone in ${totalTime} minutes!`)
  console.log(`  Hits: ${hits}`)
  console.log(`  Misses: ${misses}`)
  console.log(`  Output: ${OUTPUT_FILE}`)
}

main().catch(console.error)
