#!/usr/bin/env npx tsx
/**
 * Bulk import FDA adverse events and recalls data for ingredients.
 *
 * Queries OpenFDA for each ingredient name:
 *   - /food/event.json → adverse event count
 *   - /food/enforcement.json → recall count + recent recalls
 *
 * Usage:
 *   npx tsx scripts/import-fda.ts
 *
 * Input:  Queries D1 for ingredient names (or falls back to seed list)
 * Output: scripts/d1-ingredients-ref-fda.sql
 *
 * Then import:
 *   npx wrangler d1 execute alzhal-ingredients-ref --remote --file=scripts/d1-ingredients-ref-fda.sql
 */

import { readFileSync, createWriteStream } from 'fs'
import { execSync } from 'child_process'
import path from 'path'

const OUTPUT_FILE = path.join(process.cwd(), 'scripts', 'd1-ingredients-ref-fda.sql')
const INPUT_FILE = path.join(process.cwd(), 'scripts', 'ingredient-seed-list.json')
const DB_NAME = 'alzhal-ingredients-ref'

const CONCURRENCY = 4 // 4 concurrent (each makes 2 FDA calls = 8 total, within 240/min limit)
const BATCH_DELAY_MS = 2200 // delay between batches (4 ingredients x 2 calls = 8, needs 2+ sec)
const FETCH_TIMEOUT = 10000

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''")
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

async function fetchFDAEvents(name: string): Promise<number> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT)

  try {
    const encodedName = encodeURIComponent(`"${name}"`)
    const url = `https://api.fda.gov/food/event.json?search=products.industry_name:${encodedName}+reactions:${encodedName}&limit=1`

    const res = await fetch(url, {
      headers: { 'User-Agent': 'Alzhal-Import/1.0' },
      signal: controller.signal,
    })

    clearTimeout(timeout)
    if (!res.ok) return 0

    const data = await res.json()
    return data.meta?.results?.total || 0
  } catch {
    clearTimeout(timeout)
    return 0
  }
}

async function fetchFDARecalls(name: string): Promise<{
  total: number
  recent: Array<{ reason: string; classification: string; status: string }>
}> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT)

  try {
    const encodedName = encodeURIComponent(`"${name}"`)
    const url = `https://api.fda.gov/food/enforcement.json?search=reason_for_recall:${encodedName}&limit=3`

    const res = await fetch(url, {
      headers: { 'User-Agent': 'Alzhal-Import/1.0' },
      signal: controller.signal,
    })

    clearTimeout(timeout)
    if (!res.ok) return { total: 0, recent: [] }

    const data = await res.json()
    const total = data.meta?.results?.total || 0
    const recent = (data.results || []).slice(0, 3).map((r: any) => ({
      reason: (r.reason_for_recall || 'Unknown').slice(0, 200),
      classification: r.classification || 'Unknown',
      status: r.status || 'Unknown',
    }))

    return { total, recent }
  } catch {
    clearTimeout(timeout)
    return { total: 0, recent: [] }
  }
}

async function getNamesFromDB(): Promise<string[]> {
  try {
    const result = execSync(
      `npx wrangler d1 execute ${DB_NAME} --remote --command "SELECT name FROM ingredient_reference" --json`,
      { encoding: 'utf-8', maxBuffer: 100 * 1024 * 1024 }
    )
    const parsed = JSON.parse(result)
    const rows = parsed?.[0]?.results || []
    return rows.map((r: any) => r.name)
  } catch (e) {
    console.log('Could not query D1 for names, falling back to seed list')
    return JSON.parse(readFileSync(INPUT_FILE, 'utf-8'))
  }
}

async function processIngredient(name: string): Promise<{
  name: string
  eventCount: number
  recallCount: number
  recentRecalls: string
}> {
  const [eventCount, recalls] = await Promise.all([
    fetchFDAEvents(name),
    fetchFDARecalls(name),
  ])
  return {
    name,
    eventCount,
    recallCount: recalls.total,
    recentRecalls: JSON.stringify(recalls.recent),
  }
}

async function main() {
  console.log('Getting ingredient names from reference DB...')
  const names = await getNamesFromDB()

  if (names.length === 0) {
    console.error('No names found. Run PubChem import first.')
    process.exit(1)
  }

  console.log(`Processing ${names.length} ingredients`)
  console.log(`Estimated time: ${((names.length / CONCURRENCY * BATCH_DELAY_MS) / 1000 / 60).toFixed(0)} minutes`)

  const out = createWriteStream(OUTPUT_FILE)
  out.write('-- FDA data import for ingredients reference\n')
  out.write('-- Auto-generated by import-fda.ts\n\n')

  let updated = 0
  let skipped = 0
  const startTime = Date.now()

  for (let i = 0; i < names.length; i += CONCURRENCY) {
    const batch = names.slice(i, i + CONCURRENCY)

    const results = await Promise.all(batch.map(processIngredient))

    for (const result of results) {
      if (result.eventCount > 0 || result.recallCount > 0) {
        updated++
        out.write(
          `UPDATE ingredient_reference SET fda_adverse_event_count = ${result.eventCount}, fda_recall_count = ${result.recallCount}, fda_recent_recalls = '${escapeSQL(result.recentRecalls)}', last_fda_sync_at = datetime('now'), updated_at = datetime('now') WHERE name = '${escapeSQL(result.name.toLowerCase())}';\n`
        )
      } else {
        skipped++
        out.write(
          `UPDATE ingredient_reference SET last_fda_sync_at = datetime('now') WHERE name = '${escapeSQL(result.name.toLowerCase())}';\n`
        )
      }
    }

    const processed = Math.min(i + CONCURRENCY, names.length)
    if (processed % 200 < CONCURRENCY || processed === names.length) {
      const elapsed = (Date.now() - startTime) / 1000
      const rate = processed / elapsed
      const remaining = (names.length - processed) / rate
      console.log(
        `Progress: ${processed}/${names.length} (${updated} with data, ${skipped} empty) ` +
        `[${rate.toFixed(1)} names/sec, ~${(remaining / 60).toFixed(0)} min remaining]`
      )
    }

    await sleep(BATCH_DELAY_MS)
  }

  out.end()

  const totalTime = ((Date.now() - startTime) / 1000 / 60).toFixed(1)
  console.log(`\nDone in ${totalTime} minutes!`)
  console.log(`  With FDA data: ${updated}`)
  console.log(`  No data: ${skipped}`)
  console.log(`  Output: ${OUTPUT_FILE}`)
}

main().catch(console.error)
