#!/usr/bin/env npx tsx
/**
 * IARC Monographs → Canonical Ingredient Graph seeder.
 *
 * Reads the pre-parsed IARC classification JSON (generated by build-reference-db.py's
 * parse_iarc_pdf step) and emits SQL for the new regulatory schema:
 *   - ingredient                (canonical row, keyed by CAS when available)
 *   - ingredient_alias          (CAS number + the exact agent name from IARC)
 *   - fact_evidence             (one row: the IARC Monographs classification PDF)
 *   - regulatory_fact           (one row per agent, jurisdiction = WHO_IARC)
 *
 * Every regulatory_fact row has a verifiable source_url. No claim is stored
 * without evidence.
 *
 * Usage:
 *   npx tsx scripts/seed-iarc-cig.ts
 *
 * Input:  scripts/bulk-data/iarc-parsed.json   (generated by build-reference-db.py)
 *         OR scripts/bulk-data/iarc-classifications.pdf (will emit instructions)
 *
 * Output: scripts/d1-regulatory-iarc.sql
 *
 * Then import:
 *   npx wrangler d1 execute alzhal-regulatory --remote --file=scripts/d1-regulatory-iarc.sql
 *
 * Source:
 *   IARC Monographs on the Identification of Carcinogenic Hazards to Humans
 *   Official list URL: https://monographs.iarc.who.int/list-of-classifications/
 *   PDF: https://monographs.iarc.who.int/agents-classified-by-the-iarc/
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import path from 'path'

const BULK_DIR = path.join(process.cwd(), 'scripts', 'bulk-data')
const INPUT_JSON = path.join(BULK_DIR, 'iarc-parsed.json')
const INPUT_PDF = path.join(BULK_DIR, 'iarc-classifications.pdf')
const OUTPUT_FILE = path.join(process.cwd(), 'scripts', 'd1-regulatory-iarc.sql')

const INGESTER_NAME = 'seed-iarc-cig'
const INGESTER_VERSION = '1.0.0'
const IARC_SOURCE_NAME = 'IARC Monographs — Agents Classified by the IARC Monographs'
const IARC_SOURCE_URL = 'https://monographs.iarc.who.int/list-of-classifications/'
const IARC_PDF_URL = 'https://monographs.iarc.who.int/agents-classified-by-the-iarc/'

type IarcRecord = {
  group: '1' | '2A' | '2B' | '3'
  description: string
  agent_name: string
  cas: string
}

type IarcData = Record<string, IarcRecord>

function escapeSql(s: string | null | undefined): string {
  if (s == null) return 'NULL'
  return `'${String(s).replace(/'/g, "''")}'`
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 80)
}

function canonicalIdFromRecord(r: IarcRecord): string {
  if (r.cas && /^\d{3,7}-\d{2}-\d$/.test(r.cas)) {
    return `CAS_${r.cas.replace(/-/g, '_')}`
  }
  return `NAME_${slugify(r.agent_name)}`
}

function normalizeAlias(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function iarcStatusString(group: string, description: string): string {
  return `WHO/IARC Group ${group} — ${description}`
}

function loadIarcData(): IarcData | null {
  if (existsSync(INPUT_JSON)) {
    console.log(`Loading IARC classifications from ${INPUT_JSON}`)
    return JSON.parse(readFileSync(INPUT_JSON, 'utf-8')) as IarcData
  }

  if (existsSync(INPUT_PDF)) {
    console.error('Found iarc-classifications.pdf but no iarc-parsed.json.')
    console.error('Run the existing Python parser first:')
    console.error('  python3 scripts/build-reference-db.py')
    console.error('That will emit scripts/bulk-data/iarc-parsed.json, then re-run this seeder.')
    return null
  }

  console.error('No IARC source data found.')
  console.error('')
  console.error('Download the IARC classification list and place at:')
  console.error(`  ${INPUT_PDF}`)
  console.error('')
  console.error('Source: https://monographs.iarc.who.int/list-of-classifications/')
  console.error('Direct PDF: https://monographs.iarc.who.int/agents-classified-by-the-iarc/')
  console.error('')
  console.error('Then run:')
  console.error('  python3 scripts/build-reference-db.py   # parses PDF → iarc-parsed.json')
  console.error('  npx tsx scripts/seed-iarc-cig.ts        # re-run this seeder')
  return null
}

function main() {
  const iarc = loadIarcData()
  if (!iarc) {
    process.exit(2)
  }

  const entries = Object.values(iarc)
  console.log(`Loaded ${entries.length} IARC classifications`)

  const groupCounts: Record<string, number> = {}
  for (const r of entries) {
    groupCounts[r.group] = (groupCounts[r.group] || 0) + 1
  }
  console.log('Groups:', groupCounts)

  const snapshotDate = new Date().toISOString().slice(0, 10)
  const lines: string[] = []

  lines.push('-- ============================================================')
  lines.push(`-- IARC Monographs → Canonical Ingredient Graph seed`)
  lines.push(`-- Generated: ${new Date().toISOString()}`)
  lines.push(`-- Ingester: ${INGESTER_NAME} v${INGESTER_VERSION}`)
  lines.push(`-- Entries: ${entries.length}`)
  lines.push(`-- Source: ${IARC_SOURCE_URL}`)
  lines.push('-- ============================================================')
  lines.push('')
  // Note: D1 rejects raw BEGIN TRANSACTION. Idempotent ON CONFLICT clauses provide safety.
  lines.push('')

  lines.push(`INSERT INTO ingestion_run (ingester_name, ingester_version, status) VALUES (${escapeSql(INGESTER_NAME)}, ${escapeSql(INGESTER_VERSION)}, 'running');`)
  lines.push('')

  lines.push('-- Evidence row: one per IARC ingestion run')
  lines.push(`INSERT INTO fact_evidence (source_name, source_url, source_section, snapshot_date, language, retrieved_by)`)
  lines.push(`  VALUES (${escapeSql(IARC_SOURCE_NAME)}, ${escapeSql(IARC_SOURCE_URL)}, 'Full classification list', ${escapeSql(snapshotDate)}, 'en', ${escapeSql(`${INGESTER_NAME}:${INGESTER_VERSION}`)})`)
  lines.push('  ON CONFLICT(source_url, snapshot_date) DO NOTHING;')
  lines.push('')

  let ingredientCount = 0
  let aliasCount = 0
  let factCount = 0

  for (const r of entries) {
    const canonicalId = canonicalIdFromRecord(r)
    const primaryName = r.agent_name
    const hasCas = r.cas && /^\d{3,7}-\d{2}-\d$/.test(r.cas)

    // 1. Upsert ingredient
    lines.push(`INSERT INTO ingredient (canonical_id, primary_name, ingredient_class, cas_number, category, is_natural)`)
    lines.push(`  VALUES (${escapeSql(canonicalId)}, ${escapeSql(primaryName)}, 'substance', ${hasCas ? escapeSql(r.cas) : 'NULL'}, 'multi', 0)`)
    lines.push('  ON CONFLICT(canonical_id) DO NOTHING;')
    ingredientCount++

    // 2. Alias: original agent name
    const aliasNorm = normalizeAlias(primaryName)
    lines.push(`INSERT INTO ingredient_alias (canonical_id, alias, alias_normalized, alias_type, language_code, confidence, source)`)
    lines.push(`  VALUES (${escapeSql(canonicalId)}, ${escapeSql(primaryName)}, ${escapeSql(aliasNorm)}, 'synonym', 'en', 1.0, 'IARC')`)
    lines.push(`  ON CONFLICT(alias_normalized, alias_type, COALESCE(language_code, '')) DO NOTHING;`)
    aliasCount++

    // 3. Alias: CAS number (when present)
    if (hasCas) {
      const casNorm = normalizeAlias(r.cas)
      lines.push(`INSERT INTO ingredient_alias (canonical_id, alias, alias_normalized, alias_type, language_code, confidence, source)`)
      lines.push(`  VALUES (${escapeSql(canonicalId)}, ${escapeSql(r.cas)}, ${escapeSql(casNorm)}, 'cas', NULL, 1.0, 'IARC')`)
      lines.push(`  ON CONFLICT(alias_normalized, alias_type, COALESCE(language_code, '')) DO NOTHING;`)
      aliasCount++
    }

    // 4. Regulatory fact: the IARC classification
    const status = iarcStatusString(r.group, r.description)
    const regRef = `IARC Monographs — Group ${r.group}`
    lines.push(`INSERT INTO regulatory_fact (canonical_id, jurisdiction, fact_type, status, regulation_ref, evidence_id)`)
    lines.push(`  VALUES (${escapeSql(canonicalId)}, 'WHO_IARC', 'classification', ${escapeSql(status)}, ${escapeSql(regRef)},`)
    lines.push(`          (SELECT id FROM fact_evidence WHERE source_url = ${escapeSql(IARC_SOURCE_URL)} AND snapshot_date = ${escapeSql(snapshotDate)} LIMIT 1));`)
    factCount++
  }

  lines.push('')
  lines.push(`UPDATE ingestion_run`)
  lines.push(`  SET finished_at = datetime('now'), status = 'completed',`)
  lines.push(`      rows_inserted = ${ingredientCount + aliasCount + factCount}`)
  lines.push(`  WHERE id = (SELECT id FROM ingestion_run WHERE ingester_name = ${escapeSql(INGESTER_NAME)} AND status = 'running' ORDER BY started_at DESC LIMIT 1);`)
  lines.push('')

  writeFileSync(OUTPUT_FILE, lines.join('\n'))

  console.log('')
  console.log(`Wrote ${OUTPUT_FILE}`)
  console.log(`  Ingredients: ${ingredientCount}`)
  console.log(`  Aliases:     ${aliasCount}`)
  console.log(`  Facts:       ${factCount}`)
  console.log('')
  console.log('Next step — apply to your regulatory D1 database:')
  console.log('  npx wrangler d1 create alzhal-regulatory   # one-time')
  console.log('  # Add the binding to wrangler.toml, then:')
  console.log('  npx wrangler d1 execute alzhal-regulatory --remote --file=scripts/d1-regulatory-schema.sql')
  console.log(`  npx wrangler d1 execute alzhal-regulatory --remote --file=${path.relative(process.cwd(), OUTPUT_FILE)}`)
}

main()
